apiVersion: v1
kind: Service
metadata:
  name: prism-agent
  labels:
    {{- include "prism-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "prism-agent.selectorLabels" . | nindent 4 }}
