apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prism-agent-secrets-required
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster
  target:
    name: prism-agent-secrets-required
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: kv/data/prism/agents/managed-llm-keys