apiVersion: v1
kind: ConfigMap
metadata:
  name: prism-agent-env
data:
  # Default settings for all agents
  VERBOSE: "true"
  
  # Database and cache settings
  CACHE_STORE: "database"
  POSTGRES_URL: "postgresql://postgres:prism-agent-pgsql-password@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local:5432/prism-agent"

  # Feature Flags
  IMAGE_GEN: "true"
  # USE_OPENAI_EMBEDDING: "true"