apiVersion: apps/v1
kind: Deployment
metadata:
  name: toly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toly
  template:
    metadata:
      labels:
        app: toly
    spec:
      containers:
      - name: api
        image: toly-api
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      - name: web
        image: toly-web
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: toly
spec:
  selector:
    app: toly
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: api
    port: 3000
    targetPort: 3000
  type: LoadBalancer 