apiVersion: v1
kind: ConfigMap
metadata:
  name: prism-agent-character
  labels:
    {{- include "prism-agent.labels" . | nindent 4 }}
data:
  character.json: |
    {{- .Values.agent.config | toJson | nindent 4 }}

